[package]
name = "geo-clipper"
version = "0.3.0"
authors = ["Gérald Lelong <gerald.lelong@easymov.fr>"]
edition = "2018"
license = "ISC"
readme = "README.md"
repository = "https://github.com/lelongg/geo-clipper"
documentation = "https://docs.rs/geo-clipper/"
description = "Boolean operations on polygons"
keywords = ["geo", "polygon", "boolean"]
categories = ["algorithms"]

[dependencies]
clipper-sys = { git = "https://github.com/mkovacs/clipper-sys", branch = "mkovacs-windows-msvc" }
geo-types = "0.5.0"
